name: Update Zen Browser

on:
  # Allow manual runs and schedule three executions per day
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC
    - cron: '0 8 * * *'   # Run at 8 AM UTC
    - cron: '0 16 * * *'  # Run at 4 PM UTC

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Install Nix
      - uses: DeterminateSystems/nix-installer-action@main

      # Step 3: Run the update script
      - name: Run update.sh
        run: ./update.sh

      # Step 4: Auto commit and push any changes
      - name: Auto Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated update to Zen Browser"
          push_options: '--force'
