name: Update Zen Browser

# Define triggers for the workflow
on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies required to run `update.sh`
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y jq curl

      # Step 3: Run the update script
      - name: Run update.sh
        run: ./update.sh

      # Step 4: Commit and push changes to the repository
      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add info.json
          git commit -m "Automated update to latest Zen Browser version" || echo "No changes to commit"
          git push
